name: zowe-cli-plugin

on: [push, pull_request]

jobs:
  test:

    runs-on: ${{ matrix.os }}

    strategy:
      fail-fast: false
      matrix:
        node-version: [14.x, 16.x, 18.x]
        os: [windows-latest, ubuntu-latest, macos-latest]

    env:
      OS: ${{ matrix.os }}
      NODE: ${{ matrix.node-version }}
      NODE_OPTIONS: --max_old_space_size=4096

    timeout-minutes: 60

    concurrency:
      group: ${{ matrix.os }}-node-${{ matrix.node-version }}-ci-${{ github.ref }}
      cancel-in-progress: true

    if: (github.event_name == 'push' || github.event.pull_request.head.repo.full_name != github.repository) && !contains(github.event.head_commit.message, '[ci skip]')

    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v2
      with:
        node-version: ${{ matrix.node-version }}

    - name: Update NPM
      if: ${{ matrix.node-version == '14.x' }}
      run: npm install -g npm@7

    - name: Install Node Package Dependencies
      id: install
      run: npm ci

    - name: Windows only - Add clidriver to PATH
      id: clidriver
      if: ${{ matrix.os == 'windows-latest' }}
      run: echo "$((Get-Item .).FullName)/node_modules/ibm_db/installer/clidriver/bin" | Out-File -FilePath $env:GITHUB_PATH -Encoding utf8 -Append

    - name: Build Source
      id: build
      run: npm run build --if-present

    - name: Unit Tests
      id: unit
      if: ${{ always() && steps.build.outcome == 'success' }}
      run: npm run test:unit >> unit-tests.txt

    - name: Archive Results
      id: upload
      if: ${{ always() && steps.build.outcome == 'success' }}
      uses: actions/upload-artifact@v2
      with:
        name: ${{ matrix.os }}-${{ matrix.node-version }}-results
        path: |
          __tests__/__results__/
          unit-tests.txt

    - name: Upload Results to Codecov
      if: ${{ always() && steps.build.outcome == 'success' }}
      uses: codecov/codecov-action@v3
      with:
        env_vars: OS,NODE
